### ISSUE TITLE
Wind Speed Can't be zero

### ISSUE THREAD

**Issue by zacharycope0** [QUIC-Fire-TT/ttrs_quicfire#4]
**Feature Description**
When ever we generate a wind field we need to ensure that its >0. This will be easy to implement. 

**Getting Started**
In quic_fire.inp -> WindShifts -> build_wind_field:
![image](https://user-images.githubusercontent.com/43671145/170323207-2bd78a1a-c00e-404e-a1bd-5c5111a8fb3d.png)
change temp_speed = 0 to 
random float between 0.01-0.1

**Comment by cbonesteel** [comment]
https://github.com/QUIC-Fire-TT/ttrs_quicfire/blob/48f8c46a6915781e63913fb8591b6cc1203cbe18/ttrs_quicfire/quic_fire.py#L220-L221
This should be all that is needed. Tested by setting ```temp_speed``` equal to 0 and printing the array. None were 0.

**Comment by zacharycope0** [comment]
Perfect. As I was writing the issue I realized that I should have just change the line haha. Looks good feel free to merge to main.
